d /run/kitpro 0750 root kitpro-api -
d /var/lib/kitpro-api 0750 kitpro-api kitpro-api -
d /var/lib/kitpro-api/backups 0700 kitpro-api kitpro-api -
d /var/lib/kitpro-helper 0700 root root -
d /var/lib/kitpro-helper/backups 0700 root root -
d /var/log/kitpro 0750 root root -
d /srv/kitpro 0750 root root -
d /srv/kitpro/apps 0750 root root -
